export const cardList = [
    {
        id: 1,
        topic: "Web Design",
        title: "Название задачи",
        date: "30.10.23",
        status: "Нужно сделать",
    },
    {
        id: 2,
        topic: "Research",
        title: "Название задачи",
        date: "30.10.23",
        status: "Без статуса",
    },
    {
        id: 3,
        topic: "Research",
        title: "Название задачи",
        date: "30.10.23",
        status: "В работе",
    },
    {
        id: 4,
        topic: "Copywriting",
        title: "Название задачи",
        date: "30.10.23",
        status: "Без статуса",
    },
    {
        id: 5,
        topic: "Web Design",
        title: "Название задачи",
        date: "30.10.23",
        status: "Без статуса",
    },
    {
        id: 6,
        topic: "Copywriting",
        title: "Название задачи",
        date: "30.10.23",
        status: "Тестирование",
    },
    {
        id: 7,
        topic: "Research",
        title: "Название задачи",
        date: "30.10.23",
        status: "Готово",
    },
  ];